debug:
    inspect_books: false
    # random_seed: 1994

training:
    n_threads: 1
    n_samples: 3
    n_episodes: 10000

evaluation:
    n_samples: 1

    random_agent: false

learning:
    memory_size: 20000000
    n_tilings: 32
    n_actions: 9

    algorithm: sarsa

    group_weights: [0.65, 0.25, 0.10]

    gamma: 0.975
    lambda: 0.85

    omega: 1.0
    alpha_start: 0.001
    alpha_floor: 0.001

    beta: 0.005

policy:
    type: epsilon_greedy

    eps_init: 0.8
    eps_floor: 0.0001
    eps_T: 5000

    spread_lookback: 45

reward:
    measure: pnl_damped

    damping_factor: 0.15

    pnl_lookback: 0

    pos_weight: 0.0
    pnl_weight: 1.0

state:
    #variables: ["pos", "a_dist", "b_dist", "mpm", "spd", "vol", "imb", "svl"]
    variables: ["pos", "a_dist", "b_dist", "mpm", "spd", "abv_diff","abv_diff_ratio",
                "abv_diff_change","av_consume","av_consume_5d","bv_consume","bv_consume_5d"]
    lookback:
        mpm: 15
        vlt: 60
        svl: 60
        rsi: 100
        vwap: 100

data:
    symbols: ["000661.SZ"]
    train:
        md_dir: "../data/train/md"
        tas_dir: "../data/train/tas"
    test:
        md_dir: "../data/test/md"
        tas_dir: "../data/test/tas"
    #md_dir: "../../../temp/md"
    #tas_dir: "../../../temp/tas"
market:
    TRANSACTION_FEE: 0.0007

    target_price:
        type: midprice          #源代码有笔误

        lookback: 1

    latency:
        type: fixed

        floor: 0.0

        mu: 0.0
        sigma: 0.0

    pos_ub: 600
    pos_lb: -600

    order_size: 100

logging:
    log_learning: true
    log_backtest: true

    max_size: 50000000000
